export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_FOODTYPES = 'receive_foodtypes'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USERINFO = 'receive_user_info'
export const RESET_USERINFO = 'reset_user_info'
